services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRESS_USER: postgres
      POSTGRESS_PASSWORD: postgres
      POSTGRESS_DB: postgres
    ports:
      - 5432:5432
    volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}